name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: 'windows-latest'
          - runner: 'windows-11-arm'
          - runner: 'ubuntu-latest'
          - runner: 'ubuntu-24.04-arm'
          - runner: 'macos-latest'
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Build and Run
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
        DOTNET_GENERATE_ASPNET_CERTIFICATE: false
        DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      shell: pwsh
      run: |
        $PSNativeCommandUseErrorActionPreference = $true
        $ErrorActionPreference = 'Stop'
        $isArm64 = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture -eq 'Arm64'
        if ($IsWindows -and -not $isArm64) {
          dotnet run -- install-qt windows desktop 6.11.0 --dryrun
          dotnet run -- install-qt windows desktop 6.10.0 --dryrun
          dotnet run -- install-qt windows desktop 6.9.0 --dryrun
          dotnet run -- install-qt windows desktop 6.8.0 --dryrun
          dotnet run -- install-qt windows desktop 6.7.0 --dryrun
          dotnet run -- install-qt windows desktop 6.6.0 --dryrun
          dotnet run -- install-qt windows desktop 6.5.0 --dryrun
          dotnet run -- install-qt windows desktop 6.4.0 --dryrun
          dotnet run -- install-qt windows desktop 6.3.0 --dryrun
          dotnet run -- install-qt windows desktop 6.2.0 --dryrun
          dotnet run -- install-qt windows desktop 6.1.0 --dryrun
          dotnet run -- install-qt windows desktop 6.0.0 --dryrun
          dotnet run -- install-qt windows desktop 5.15.0 --dryrun
          dotnet run -- install-qt windows desktop 5.12.0 --dryrun
          dotnet run -- install-qt all_os android 6.11.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt all_os android 6.10.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt all_os android 6.9.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt all_os android 6.8.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt all_os android 6.7.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.6.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.5.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.4.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.3.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.2.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.1.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 6.0.0 android_arm64_v8a --dryrun
          dotnet run -- install-qt windows android 5.15.0 android --dryrun
          dotnet run -- install-qt windows android 5.12.0 android_arm64_v8a --dryrun
        }
        if ($IsWindows -and $isArm64) {
          dotnet run -- install-qt windows_arm64 desktop 6.11.0 --dryrun
          dotnet run -- install-qt windows_arm64 desktop 6.10.0 --dryrun
          dotnet run -- install-qt windows_arm64 desktop 6.9.0 --dryrun
          dotnet run -- install-qt windows_arm64 desktop 6.8.0 --dryrun
        }
        if ($IsLinux -and -not $isArm64) {
          dotnet run -- install-qt linux desktop 6.11.0 --dryrun
          dotnet run -- install-qt linux desktop 6.10.0 --dryrun
          dotnet run -- install-qt linux desktop 6.9.0 --dryrun
          dotnet run -- install-qt linux desktop 6.8.0 --dryrun
          dotnet run -- install-qt linux desktop 6.7.0 --dryrun
          dotnet run -- install-qt linux desktop 6.6.0 --dryrun
          dotnet run -- install-qt linux desktop 6.5.0 --dryrun
          dotnet run -- install-qt linux desktop 6.4.0 --dryrun
          dotnet run -- install-qt linux desktop 6.3.0 --dryrun
          dotnet run -- install-qt linux desktop 6.2.0 --dryrun
          dotnet run -- install-qt linux desktop 6.1.0 --dryrun
          dotnet run -- install-qt linux desktop 6.0.0 --dryrun
          dotnet run -- install-qt linux desktop 5.15.0 --dryrun
          dotnet run -- install-qt linux desktop 5.12.0 --dryrun
          dotnet run -- install-qt all_os wasm 6.11.0 wasm_singlethread --dryrun
          dotnet run -- install-qt all_os wasm 6.10.0 wasm_singlethread --dryrun
          dotnet run -- install-qt all_os wasm 6.9.0 wasm_singlethread --dryrun
          dotnet run -- install-qt all_os wasm 6.8.0 wasm_singlethread --dryrun
          dotnet run -- install-qt all_os wasm 6.7.0 wasm_singlethread --dryrun
          dotnet run -- install-qt linux wasm 6.6.0 wasm_singlethread --dryrun
          dotnet run -- install-qt linux wasm 6.5.0 wasm_singlethread --dryrun
          dotnet run -- install-qt linux wasm 6.4.0 wasm_32 --dryrun
          dotnet run -- install-qt linux wasm 6.3.0 wasm_32 --dryrun
          dotnet run -- install-qt linux wasm 6.2.0 wasm_32 --dryrun
          dotnet run -- install-qt linux wasm 5.15.0 wasm_32 --dryrun
        }
        if ($IsLinux -and $isArm64) {
          dotnet run -- install-qt linux_arm64 desktop 6.11.0 --dryrun
          dotnet run -- install-qt linux_arm64 desktop 6.10.0 --dryrun
          dotnet run -- install-qt linux_arm64 desktop 6.9.0 --dryrun
          dotnet run -- install-qt linux_arm64 desktop 6.8.0 --dryrun
          dotnet run -- install-qt linux_arm64 desktop 6.7.0 --dryrun
        }
        if ($IsMacOS) {
          dotnet run -- install-qt mac desktop 6.11.0 --dryrun
          dotnet run -- install-qt mac desktop 6.10.0 --dryrun
          dotnet run -- install-qt mac desktop 6.9.0 --dryrun
          dotnet run -- install-qt mac desktop 6.8.0 --dryrun
          dotnet run -- install-qt mac desktop 6.7.0 --dryrun
          dotnet run -- install-qt mac desktop 6.6.0 --dryrun
          dotnet run -- install-qt mac desktop 6.5.0 --dryrun
          dotnet run -- install-qt mac desktop 6.4.0 --dryrun
          dotnet run -- install-qt mac desktop 6.3.0 --dryrun
          dotnet run -- install-qt mac desktop 6.2.0 --dryrun
          dotnet run -- install-qt mac desktop 6.1.0 --dryrun
          dotnet run -- install-qt mac desktop 6.0.0 --dryrun
          dotnet run -- install-qt mac desktop 5.15.0 --dryrun
          dotnet run -- install-qt mac desktop 5.12.0 --dryrun
          dotnet run -- install-qt mac ios 6.11.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.10.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.9.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.8.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.7.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.6.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.5.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.4.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.3.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.2.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.1.0 ios --dryrun
          dotnet run -- install-qt mac ios 6.0.0 ios --dryrun
          dotnet run -- install-qt mac ios 5.15.0 ios --dryrun
          dotnet run -- install-qt mac ios 5.12.0 ios --dryrun
        }
